# Use an official Node.js image v25.3
FROM node@sha256:a2f09f3ab9217c692a4e192ea272866ae43b59fabda1209101502bf40e0b9768

WORKDIR /app

COPY src/package*.json ./
RUN npm install

COPY src .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]