FROM node:25-bookworm-slim@sha256:32f45869cf02c26971de72c383d5f99cab002905ed8b515b56df925007941782

WORKDIR /app

COPY src/package*.json ./
RUN npm install

COPY src .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]