{
 "title": "API Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "The average request latency over the last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (route) (\r\n  rate(http_request_duration_seconds_sum[5m])\r\n)\r\n/\r\nsum by (route) (\r\n  rate(http_request_duration_seconds_count[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95% Latency Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency distribution by route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (route, le) (\r\n  rate(http_request_duration_seconds_bucket[10m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}